name: Run Vitest Tests

on:
  pull_request: {}

jobs:
  frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
        working-directory: ./frontend
      - name: Croppie installed?
        run: npm ls croppie || echo "Croppie NOT installed"
        working-directory: ./frontend
      - run: npm run test-frontend -- --run
        working-directory: ./frontend

  backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run test-backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}